version: '3.8'

services:
  load-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    image: load-analyzer:latest
    container_name: load-analyzer
    hostname: load-analyzer
    
    # 网络和进程命名空间设置
    network_mode: host
    pid: host
    
    # 卷挂载
    volumes:
      - /proc:/host/proc:ro          # 进程信息
      - /sys:/host/sys:ro            # 系统信息
      - /:/host/root:ro              # 主机根目录（只读）
      - ./output:/output:rw          # 输出目录
      - ./config:/app/config:ro      # 配置目录
    
    # 环境变量
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ROOT=/host/root
      - PYTHONUNBUFFERED=1
    
    # 权限设置
    cap_add:
      - SYS_PTRACE    # 允许追踪进程
      - SYS_ADMIN     # 允许系统管理操作
      - NET_ADMIN     # 允许网络管理
    
    security_opt:
      - apparmor:unconfined  # 禁用AppArmor限制
    
    # 默认命令（可以被覆盖）
    command: ["--help"]
    
    # 资源限制（可选）
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    
    # 重启策略
    restart: "no"

  # 服务用于交互式运行
  load-analyzer-interactive:
    extends: load-analyzer
    container_name: load-analyzer-interactive
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
    
networks:
  default:
    external: true
    name: host
