alert_slack_channel: null
alert_slack_token: null
alert_webhook_url: null
context_switches_threshold: 10000
cpu_threshold: 80.0
disk_io_read_threshold: 104857600
disk_io_write_threshold: 104857600
enable_alerts: false
enable_colors: true
enable_history: false
enable_prometheus: false
history_file: null
history_retention_days: 7
interrupts_threshold: 5000
iowait_threshold: 30.0
load_threshold_multiplier: 1.5
memory_threshold: 80.0
output_file: null
output_format: text
prometheus_port: 8000
sample_count: 1
sample_interval: 1
swap_threshold: 50.0
tcp_backlog_threshold: 100
tcp_connections_threshold: 1000
top_processes_count: 10
